### PR TITLE
Add translation of Korean version

### PR DESCRIPTION
**Pull request by voidsatisfaction**
I think it will be better translation if I can get revision from other Korean developers :D

### CODE REVIEW

**Comment by kazup01** [comment]
Thanks @voidsatisfaction 😄🍻 We will add it to official page tomorrow :)

**Comment by voidsatisfaction** [comment]
@kazup01 Yeah. As a contributor and user, It is cool to have multi-language landing page. Nice job.

**Comment by kazup01** [comment]
Korean page is out! Thank you @voidsatisfaction 🎉

**Comment by kazup01** [comment]
https://boostnote.io/kr/

**Comment by voidsatisfaction** [comment]
@kazup01 I read and saw the Korean landing page. I wanted to change title because current page is a little bit tired to read(too long). Can I do that?

**Comment by voidsatisfaction** [comment]
# BEFORE

screen shot 2017-12-22 at 8 34 43 pm


# AFTER

screen shot 2017-12-22 at 8 33 07 pm

**Comment by Rokt33r** [comment]
@voidsatisfaction Sounds reasonable. Could you create another PR again?

**Pull request merged**
