### PR TITLE
DK - Danish

### PR DESCRIPTION
**Pull request by chiangs**
Danish version of en.md

### CODE REVIEW

**Comment by chiangs** [comment]
Some words could either be in danish or using english as much of the technical terms are commonly understood.

For example: 
Fællesskab -> Community
Uddrag -> snippets

**Comment by kazup01** [comment]
Thanks @chiangs ! We will add it to official page tomorrow :)

**Comment by chiangs** [comment]
Do you think you could credit the individual contributors on the main page readme? That would really be appreciated :)

**Comment by kazup01** [comment]
That's nice! I will add awesome contributors name on Readme tomorrow. Thank you for your suggestion :)

**Comment by chiangs** [comment]
Awesome, thanks!

**Comment by chiangs** [comment]
@kazup01 don't forget this one! 😁

**Comment by chiangs** [comment]
@kazup01 Is there a reason this PR is not accepted? Let me know if I need to fix anything, thanks :)

**Comment by kazup01** [comment]
Sorry for waiting! Danish page is out ;)
https://boostnote.io/dk/

Thanks for your help!

**Pull request merged**
